name: Deploy API
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'intg'
      to_deploy:
        description: 'Version to deploy'
        required: true

permissions:
  id-token: write
  contents: read
  actions: write
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set environment specific account name
        run: gh workflow run gh workflow run nationalarchives/tdr-e2e-tests/.github/workflows/ci.yml@move-to-github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


