name: Run API tests
on:
  pull_request:
  push:
permissions:
  id-token: write
  contents: write
  actions: write
jobs:
  test:
    runs-on: ubuntu-latest
    environment: intg
    steps:
      - name: Checkout
        run: gh workflow run "Deploy API" -f environment=intg -f to_deploy=v181
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}